// <auto-generated />
using System;
using EnvironmentApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnvironmentApi.Migrations
{
    [DbContext(typeof(EnvironmentContext))]
    [Migration("20200925080251_addUser")]
    partial class addUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnvironmentApi.Models.DeviceStatusModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("CPUOccupancyRate")
                        .HasColumnType("float");

                    b.Property<float>("CPUTemperature")
                        .HasColumnType("float");

                    b.Property<float>("HDDOccupancyRate")
                        .HasColumnType("float");

                    b.Property<float>("RAMOccupancyRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime");

                    b.Property<float>("SDCardOccupancyRate")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("DeviceStatus");
                });

            modelBuilder.Entity("EnvironmentApi.Models.EnvironmentModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Humidity")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime");

                    b.Property<float>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Environment");
                });

            modelBuilder.Entity("EnvironmentApi.Models.UserModel", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserName = "admin",
                            Email = "admin@admin.com",
                            Password = "PBK+UIN0ifA9lVueYaEM8g==",
                            Role = "public::admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
