// <auto-generated />

using System;
using EnvironmentApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnvironmentApi.Migrations
{
    [DbContext(typeof(EnvironmentContext))]
    partial class EnvironmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnvironmentApi.Models.DeviceStatusModel", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<float>("CPUOccupancyRate")
                    .HasColumnType("float");

                b.Property<float>("CPUTemperature")
                    .HasColumnType("float");

                b.Property<float>("HDDOccupancyRate")
                    .HasColumnType("float");

                b.Property<float>("RAMOccupancyRate")
                    .HasColumnType("float");

                b.Property<DateTime>("RecordTime")
                    .HasColumnType("datetime");

                b.Property<float>("SDCardOccupancyRate")
                    .HasColumnType("float");

                b.HasKey("ID");

                b.ToTable("DeviceStatus");
            });

            modelBuilder.Entity("EnvironmentApi.Models.EnvironmentModel", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<float>("Humidity")
                    .HasColumnType("float");

                b.Property<DateTime>("RecordTime")
                    .HasColumnType("datetime");

                b.Property<float>("Temperature")
                    .HasColumnType("float");

                b.HasKey("ID");

                b.ToTable("Environment");
            });
#pragma warning restore 612, 618
        }
    }
}